InvoicingAppBrighamMoll/Controllers/UserAccountsController.cs
using InvoicingAppBrighamMoll.Models;
using InvoicingAppBrighamMoll.Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

// Brigham Moll - 11/18/2018

namespace InvoicingAppBrighamMoll.Controllers
{
    /// <summary>
    /// Controller for the main login page. Handles user and
    /// manager logins.
    /// </summary>
    public class UserAccountsController : Controller
    {
        // Constants
        private const string MANAGER_NAME_ONE = "Ray";
        private const string MANAGER_NAME_TWO = "Amanda";
        private const string LOGIN_TYPE_MANAGER = "Manager Login";
        private const string LOGIN_TYPE_USER = "User Login";

        /// <summary>
        /// Initially when a user goes to the site, they will be sent here.
        /// </summary>
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.ErrorMsg = HttpContext.Cache["errMsg"];
            // Wipe info from before, they have to login again.
            HttpContext.Cache["userName"] = "";
            HttpContext.Cache["userIsManager"] = false;

            return View();
        }

        /// <summary>
        /// If user logs in with the form, they will be sent here.
        /// </summary>
        /// <param name="userName">Username entered by user.</param>
        /// <param name="passWord">Password entered by user.</param>
        [HttpPost]
        public ActionResult Index(string userName, string passWord)
        {
            // Password should be backwords lowercase username.
            string lowerName = userName.ToLower();
            char[] arr = lowerName.ToCharArray();
            Array.Reverse(arr);
            string correctPassword = new string(arr);

            // Check password.
            if (passWord == correctPassword)
            {
                // User Login was pressed.
                if (Request.Form["action"] == LOGIN_TYPE_USER)
                {
                    // Anyone is allowed.
                    ViewBag.Username = userName;
                    HttpContext.Cache["userName"] = userName;
                    HttpContext.Cache["userIsManager"] = false;
                    HttpContext.Cache["errMsg"] = "";
                    return RedirectToAction("Landing");
                }
                // Manager Login was pressed.
                else if (Request.Form["action"] == LOGIN_TYPE_MANAGER)
                {
                    // 'Amanda' and 'Ray' only.
                    if(userName == MANAGER_NAME_ONE || userName == MANAGER_NAME_TWO)
                    {
                        ViewBag.Username = userName;
                        HttpContext.Cache["userName"] = userName;
                        HttpContext.Cache["userIsManager"] = true;
                        HttpContext.Cache["errMsg"] = "";
                        return RedirectToAction("Landing");
                    }
                    else
                    {
                        HttpContext.Cache["errMsg"] = "Manager account of name "+ userName + " not found.";
                        return View();
                    }
                }
                else
                {
                    // This should never happen.
                    return Content("ERROR!");
                }
            }
            else
            {
                HttpContext.Cache["errMsg"] = "Invalid username or password.";
                return View();
            }
        }

        /// <summary>
        /// The page one gets to after logging in.
        /// </summary>
        public ActionResult Landing()
        {
            ViewBag.Username = HttpContext.Cache["userName"];
            ViewBag.ErrorMsg = HttpContext.Cache["errMsg"];
            return View();
        }

        /// <summary>
        /// Allows a user to add an invoice. 
        /// </summary>
        [HttpGet]
        public ActionResult AddInvoice()
        {
            if ((string)HttpContext.Cache["userName"] == "")
            {
                // Didn't log in, redirect to login.
                HttpContext.Cache["errMsg"] = "Please log in first.";
                return RedirectToAction("Index");
            }

            Invoice model = new Invoice();
            return View(model);
        }

        /// <summary>
        /// Submits an invoice. (If valid)
        /// </summary>
        [HttpPost]
        public ActionResult AddInvoice(Invoice model)
        {
            if ((string)HttpContext.Cache["userName"] == "")
            {
                // Didn't log in, redirect to login.
                HttpContext.Cache["errMsg"] = "Please log in first.";
                return RedirectToAction("Index");
            }

            // If not a valid invoice, show errors and do not add.
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if(HttpContext.Cache["invoiceStorage"] == null)
            {
                // Make storage if non-existent.
                IInvoiceStorage invoiceStorage = new InvoiceStorage();
                HttpContext.Cache["invoiceStorage"] = invoiceStorage;
            }

            // Determine next invoice number. (NEW: USE THE WEB API TO DETERMINE NEXT INVOICE NUMBER)
            if(HttpContext.Cache["nextInvoiceNum"] == null)
            {
                HttpContext.Cache["nextInvoiceNum"] = "INV0";
            }
            else
            {
                // Retrieve last invoice ID.
                string currentId = HttpContext.Cache["nextInvoiceNum"].ToString();

                // Call WEB API and get new invoice ID from there by passing in the current one.
                string newInvoiceNum = GetNewInvoiceNumberFromWebApi(currentId);

                // Save the new invoice ID.
                HttpContext.Cache["nextInvoiceNum"] = newInvoiceNum;
            }
            // Save invoice with new ID.
            ((IInvoiceStorage)HttpContext.Cache["invoiceStorage"]).AddInvoice(model, HttpContext.Cache["nextInvoiceNum"].ToString());
            ViewBag.Username = HttpContext.Cache["userName"];
            return RedirectToAction("Landing");
        }

        /// <summary>
        /// Calls the WEB API to get the new invoice number.
        /// </summary>
        /// <param name="lastInvoiceNum"> The last invoice number. </param>
        /// <returns> The new invoice number. </returns>
        public static string GetNewInvoiceNumberFromWebApi(string lastInvoiceNum)
        {
            string newInvoiceNum = "";
            // Convert old ID to just the numbers.
            int oldIdNoLetters = int.Parse(lastInvoiceNum.Substring(3));
            // Call the WEB API get method with the lastInvoiceNum to get the new one.
            using (var client = new HttpClient())
            {
                // State address of Web API
                client.BaseAddress = new Uri("http://localhost:17247/api/values/");
                // Send the GET request... with the last invoice num
                var response = client.GetAsync(oldIdNoLetters.ToString());
                response.Wait();
                // After getting result, if successful, store new invoice num.
                var result = response.Result;

                if(result.IsSuccessStatusCode)
                {
                    var read = result.Content.ReadAsAsync<string>();
                    read.Wait();

                    // Take the result, containing the returned ID string.
                    newInvoiceNum = read.Result.ToString();
                }
                else
                {
                    // Otherwise, print an error message.
                    Console.WriteLine("ERROR WITH SERVER");
                }
            }
            // Return the new invoice num.
            return newInvoiceNum;
        }

        /// <summary>
        /// Allows managers to review invoices. Will redirect regular users.
        /// </summary> 
        public ActionResult ReviewReceiveables()
        {
            if ((string)HttpContext.Cache["userName"] == "")
            {
                // Didn't log in, redirect to login.
                HttpContext.Cache["errMsg"] = "Please log in first.";
                return RedirectToAction("Index");
            }

            // Check if user is a manager. If not, redirect them to the landing page.
            if ((bool)HttpContext.Cache["userIsManager"] == false)
            {
                // Redirect to landing.
                HttpContext.Cache["errMsg"] = "You are not a manager, you cannot access that.";
                ViewBag.Username = HttpContext.Cache["userName"];
                return RedirectToAction("Landing");
            }

            if (((IInvoiceStorage)HttpContext.Cache["invoiceStorage"]) != null)
            {
                ViewBag.StoredInvoices = ((IInvoiceStorage)HttpContext.Cache["invoiceStorage"]);
            }
            else
            {
                ViewBag.StoredInvoices = new InvoiceStorage();
            }
            return View();
        }

        /// <summary>
        /// Allows a manager to edit an invoice.
        /// </summary>
        /// <param name="invoiceNumber">Invoice number of this invoice.</param>
        [HttpGet]
        public ActionResult EditInvoice(string invoiceNumber)
        {
            if ((string)HttpContext.Cache["userName"] == "")
            {
                // Didn't log in, redirect to login.
                HttpContext.Cache["errMsg"] = "Please log in first.";
                return RedirectToAction("Index");
            }

            // Check if user is a manager. If not, redirect them to the landing page.
            if ((bool)HttpContext.Cache["userIsManager"] == false)
            {
                // Redirect to landing.
                HttpContext.Cache["errMsg"] = "You are not a manager, you cannot access that.";

InvoicingAppBrighamMoll/Views/UserAccounts/AddInvoice.cshtml
@using InvoicingAppBrighamMoll.Models
@model InvoicingAppBrighamMoll.Models.Invoice
@{
    ViewBag.Title = "AddInvoice";
}

<h2>Add Invoice</h2>

@using (Html.BeginForm())
{
<div>
    <div>
        @Html.LabelFor(x => x.ClientName)
        @Html.TextBoxFor(x => x.ClientName)
        @Html.ValidationMessageFor(x => x.ClientName)
    </div>
    <div>
        @Html.LabelFor(x => x.ClientAddress)
        @Html.TextBoxFor(x => x.ClientAddress)
        @Html.ValidationMessageFor(x => x.ClientAddress)
    </div>
    <div>
        @Html.LabelFor(x => x.DateShipment)
        @Html.TextBoxFor(x => x.DateShipment)
        @Html.ValidationMessageFor(x => x.DateShipment)
    </div>
    <div>
        @Html.LabelFor(x => x.PayDueDate)
        @Html.TextBoxFor(x => x.PayDueDate)
        @Html.ValidationMessageFor(x => x.PayDueDate)
    </div>
    <div>
        @Html.LabelFor(x => x.ProdName)
        @Html.TextBoxFor(x => x.ProdName)
        @Html.ValidationMessageFor(x => x.ProdName)
    </div>
    <div>
        @Html.LabelFor(x => x.ProdQuantity)
        @Html.TextBoxFor(x => x.ProdQuantity)
        @Html.ValidationMessageFor(x => x.ProdQuantity)
    </div>
    <div>
        @Html.LabelFor(x => x.UnitPrice)
        @Html.TextBoxFor(x => x.UnitPrice)
        @Html.ValidationMessageFor(x => x.UnitPrice)
    </div>
    <div>
        @Html.LabelFor(x => x.CurrType)
        @Html.DropDownList("CurrType",
                    new SelectList(Enum.GetValues(typeof(CurrencyType))),
                    "Select Currency Type",
                    new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CurrType)
    </div>
    <div>
        <input type="submit" value="Add Invoice" />
    </div>
</div>
}

InvoicingAppBrighamMoll/Views/UserAccounts/EditInvoice.cshtml
@using InvoicingAppBrighamMoll.Models
@model InvoicingAppBrighamMoll.Models.Invoice
@{
    ViewBag.Title = "EditInvoice";
}

<h2>Edit Invoice</h2>

@using (Html.BeginForm())
{
    <div>
        <div>
            @Html.LabelFor(x => x.ClientName)
            @Html.TextBoxFor(x => x.ClientName)
            @Html.ValidationMessageFor(x => x.ClientName)
        </div>
        <div>
            @Html.LabelFor(x => x.ClientAddress)
            @Html.TextBoxFor(x => x.ClientAddress)
            @Html.ValidationMessageFor(x => x.ClientAddress)
        </div>
        <div>
            @Html.LabelFor(x => x.DateShipment)
            @Html.TextBoxFor(x => x.DateShipment)
            @Html.ValidationMessageFor(x => x.DateShipment)
        </div>
        <div>
            @Html.LabelFor(x => x.PayDueDate)
            @Html.TextBoxFor(x => x.PayDueDate)
            @Html.ValidationMessageFor(x => x.PayDueDate)
        </div>
        <div>
            @Html.LabelFor(x => x.ProdName)
            @Html.TextBoxFor(x => x.ProdName)
            @Html.ValidationMessageFor(x => x.ProdName)
        </div>
        <div>
            @Html.LabelFor(x => x.ProdQuantity)
            @Html.TextBoxFor(x => x.ProdQuantity)
            @Html.ValidationMessageFor(x => x.ProdQuantity)
        </div>
        <div>
            @Html.LabelFor(x => x.UnitPrice)
            @Html.TextBoxFor(x => x.UnitPrice)
            @Html.ValidationMessageFor(x => x.UnitPrice)
        </div>
        <div>
            @Html.LabelFor(x => x.CurrType)
            @Html.DropDownList("CurrType",
                        new SelectList(Enum.GetValues(typeof(CurrencyType))),
                        "Select Currency Type",
                        new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CurrType)
        </div>
        <div>
            <input type="submit" value="Save Invoice" />
        </div>
    </div>
}

InvoicingAppBrighamMoll/Views/UserAccounts/Index.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<form method="post">
    <h4>@ViewBag.ErrorMsg</h4>
    <div class="container">
        <label for="userName"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="userName" required><br /><br />

        <label for="passWord"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="passWord" required><br /><br />

        <input type="submit" name="action" value="User Login" />
        <input type="submit" name="action" value="Manager Login" />
    </div>
</form>

InvoicingAppBrighamMoll/Views/UserAccounts/Landing.cshtml
@{
    ViewBag.Title = "Landing";
}

<h1>@ViewBag.ErrorMsg</h1>
<h2>Welcome, @ViewBag.Username! Select an option.</h2>

@Html.ActionLink("Add Invoice", "AddInvoice") <br />
@Html.ActionLink("Review Recieveables (Managers only)", "ReviewReceiveables")

InvoicingAppBrighamMoll/Views/UserAccounts/ReviewReceiveables.cshtml
@using InvoicingAppBrighamMoll.Models
@using InvoicingAppBrighamMoll.Storage
@{
    ViewBag.Title = "Review Receiveables";

    // Use LINQ to query and find all unresolved invoices to display!
    List<Invoice> invoiceList = ((IInvoiceStorage)ViewBag.StoredInvoices).InvoiceList;
    var query = invoiceList.FindAll(invoiceEnt => invoiceEnt.TotalPrice > 0);
    // Loop through the query down below to fill out the list of invoices.
}

<h2>Review Receiveables</h2>

@Html.ActionLink("Add Invoice", "AddInvoice")

<div class="panel-body">
    <table class="table table-striped table-condensed table-bordered">
        <thead>
            <tr>
                <th class="text-center col-xs-1">Invoice Number</th>
                <th>Client Name</th>
                <th class="text-right">Total</th>
                <th class="text-center">Payment Due</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var invoiceEnt in query) // Use LINQ query from above to populate list.
            {
                <tr>
                    <td class="text-center col-xs-1">@Html.ActionLink(invoiceEnt.InvoiceNumber, "EditInvoice", new { InvoiceNumber = invoiceEnt.InvoiceNumber })</td>
                    <td>@Html.ActionLink(invoiceEnt.ClientName, "EditInvoice", new { InvoiceNumber = invoiceEnt.InvoiceNumber })</td>
                    <td class="text-right">@invoiceEnt.TotalPrice</td>
                    <td class="text-center">@invoiceEnt.PayDueDate</td>
                    <td class="text-center">
                        @using (Html.BeginForm("ResolveInvoice", "UserAccounts"))
                        {
                            @Html.Hidden("InvoiceNumber", invoiceEnt.InvoiceNumber)
                            <input type="submit" class="btn btn-default btn-sm" value="Mark as paid" />
                        }
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th></th>
                <th class="text-left text-danger">Total Receivables: </th>
                <th class="text-right text-danger">@(((decimal)(((IInvoiceStorage)ViewBag.StoredInvoices).TotalReceivables)).ToString("c"))</th>
                <th></th>
            </tr>
        </tfoot>

    </table>
</div>